---
- include: variable-check.yml
  vars:
    playbook: server.yml

- name: Determine Remote User
  hosts: web:&{{ env }}
  gather_facts: false
  roles:
    - { role: remote-user, tags: [remote-user, always] }

- name: Configure server
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: common, tags: [common] }
    # - { role: swapfile, swapfile_size: 1GB, tags: [swapfile] }
    # - { role: fail2ban, tags: [fail2ban] }
    # - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    # - { role: mariadb, tags: [mariadb] } # when: not mysql_remote_database
    # - { role: ssmtp, tags: [ssmtp, mail] }
    # - { role: php, tags: [php] }
    # - { role: memcached, tags: [memcached] }
    # - { role: apache, tags: [apache] }
    # - { role: logrotate, tags: [logrotate] }
    # - { role: composer, tags: [composer] }
    # - { role: wp-cli, tags: [wp-cli] }
    # - { role: prince, tags: [prince] }
    # - { role: letsencrypt, tags: [letsencrypt] } # when: letsencrypt_enabled
    # - { role: pressbooks-setup, tags: [pressbooks, pressbooks-setup] }
