---
- name: Install Prince
  yum:
    name: "{{ prince_package_uri }}"
    state: present
- name: Upload license
  copy:
    src: "{{ prince_license_path }}"
    dest: /usr/lib/prince/license/license.dat.new
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
- name: Check for presence of existing license
  stat:
    path: /usr/lib/prince/license/license.dat
    register: license_stat
- name: Backup old license
  command: mv /usr/lib/prince/license/license.dat /usr/lib/prince/license/license.dat.old
  when: license_stat.stat.exists
- name: Install new license
  command: mv /usr/lib/prince/license/license.dat.new /usr/lib/prince/license/license.dat
