---
- name: Validate Ansible version
  fail:
    msg: |
      Your Ansible version is {{ ansible_version.full | default('unknown') }}.
      Please install a version of Ansible that meets these requirements:
      {% for item in ansible_requirements %}
        {{ item.operator }} {{ item.version }}
      {% endfor %}
  when: ansible_version is not defined or false in [{% for item in ansible_requirements %}{{ ansible_version.full | version_compare(item.version, item.operator) }},{% endfor %}]
  run_once: true

- name: Checking essentials
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - curl
  - git

- name: Validate timezone variable
  stat:
    path: /usr/share/zoneinfo/{{ default_timezone }}
  register: timezone_path
  changed_when: false

- name: Explain timezone error
  fail:
    msg: "{{ default_timezone }} is not a valid timezone. For a list of valid timezones, check https://php.net/manual/en/timezones.php"
  when: not timezone_path.stat.exists

- name: Get current timezone
  command: cat /etc/localtime
  register: current_timezone
  changed_when: false

- name: Set timezone
  command: timedatectl set-timezone {{ default_timezone }}
  when: current_timezone.stdout != default_timezone
